### ISSUE TITLE
Move all secrets to a common directory?

### ISSUE THREAD

**Issue by 3noch** [grafted-in/wordpress-nginx-nix#12]
@niklaswallerstedt had the idea of putting all files that need to be kept secret in one directory. This would remove a some complexity and add predictability. Up till now I've been relying on `git-crypt status -e` to tell me what files are encrypted, which works pretty well. But there is an advantage to having a very simple scheme to know which files will be encrypted and which ones won't. Another possible benefit to putting everything in one directory is that it would make it much easier to pull those files out into submodule, which could be a git repo with different permissions. It could even be symlinked to a vault of some sort.

The only downside is that it's a bit more awkward to reference several totally unrelated files that are all in one directory. The natural organization scheme you'd expect gets broken. I'm not sure this is a meaningful problem though in a small project like this.

Any other thoughts?

**Comment by niklaswallerstedt** [comment]
@3noch I could go either way on this one and I would agree that given the size of the project it doesn't really matter. Close it?

**Comment by 3noch** [comment]
Ok cool. We can revisit if anyone feels it's not good as-is.
