### ISSUE TITLE
Plugin activation

### ISSUE THREAD

**Issue by niklaswallerstedt** [grafted-in/wordpress-nginx-nix#15]
@3noch Regarding #14 and plugin activation. I would use [wp-cli for this as well](http://wp-cli.org/commands/plugin/activate/) and extend the install script. You could either pass a list of plugins to activate or activate them all with the `--all` option.

**Comment by 3noch** [comment]
@niklaswallerstedt Sweet! I could extend `plugins.nix` to tack on a bool for each plugin. Then your `plugins.nix` file could list both the source and whether or not you want it activated. That does make the plugin code a bit more complex, but I might be able to do it without much disruption. What do you think?

**Comment by niklaswallerstedt** [comment]
I think I'd also prefer to keep it in there. I'm curious how you would extract all the plugin names that should be activated? Passing it to the script then should be pretty straightforward.

**Comment by 3noch** [comment]
I already have to loop over the list of plugins to copy their source into the package. I could also loop over them (`map`) to generate a list of names that would be used to produce a command to give to `wp-cli`.

**Comment by niklaswallerstedt** [comment]
Ah, I see 👍
